"Title": "OninesixY的小站"
"Subtitle": "包装成网站的垃圾站"
"Description": "我自己都无法理解我搭建这个网站是何意味"
"ColorPack": "color.yml"
"DefaultColor": "MetroBlue"
"DocsFolder": "Docs"
"PublicFolder": "Public"
"ThemeFolder": "Themes"
"DefaultTheme": "Met"